# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

hydra:
  job:
    chdir: True
    name: SFM_withoutLowCond
  run:
    dir: ./training_output/${hydra:job.name}

# Where to save the results
outdir: .

## Main options
defaults:
  - config_train_base

arch: ddpmpp-cwb
# Network architecture [ddpmpp, ddpmpp-cwb, ncsnpp, adm, ddpmpp-cwb-v0-regression]
precond: sfmloss
  # Preconditioning & loss function [vp, ve, edm, unetregression, resloss, sfmloss]
task: sfm
  # Which model to train [regression, diffusion, sfm]
# hr_mean_conditioning: True
  # High-res mean (regression's output) as additional condition
sfm:
  encoder_type: 1x1conv
  # Different encoder types for SFM: 1x1conv, unet
  sigma_distribution: lognormal
  # Distribution of the noise sigma [uniform, lognormal]
  sigma_min: 0.01
  # Minimum value of the noise sigma
  sigma_max: 1.0
  # Maximum value of the noise sigma
  denoiser_type: x_prediction
  # Type of denoiser [x_prediction, epsilon]
  era_conditioning: False
  # Conditioning for the diffusion model on the upsampled ERA data [True, False]

wandb_mode: offline